### ISSUE TITLE
Update tests to latest conventions, split between unit and system

### ISSUE THREAD

**Issue by jcredding** [redding/dat-worker-pool#14]
The tests for `DatWorkerPool` are a little out of date with our conventions. Specifically:

* The  `DatWorkerPool` unit tests are really more system tests. They are mostly good as-is, they should just be organized as system tests and replace the existing system tests as they cover everything it does.
* The unit tests should be redone using fakes/spies for the individual pieces. The `DatWorkerPool` tests should probably spy `Worker` to avoid running real threads and managing them.
* Use `Assert::Factory` for all fake data.
* Update context names and descriptions, match our latest conventions.

This is not high priority because the tests provide good coverage and we don't make many changes to the gem. The only issue is the unit tests are fairly fragile and not as easy to debug or extend.

**Comment by kellyredding** [comment]
@jcredding are we good to close this now?  I feel like we are after our last few rounds of tests and updating to get things passing on ruby2.

**Comment by jcredding** [comment]
A few extra commits/PRs that were related to this effort (I think):

90e4b6e9aa271320ae8ce053eb43eb387ff05f39
#41 
#42 

@kellyredding - Yeah I think the tests are good to go now.
